/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "index": {
    name: "index",
    description: "",
    type: "registry:style",
    registryDependencies: ["cx"],
    files: [],
    component: null,
    categories: undefined,
    meta: undefined,
  },
  "cx": {
    name: "cx",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/lib/cx.ts",
      type: "registry:lib",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/lib/cx.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-demo": {
    name: "sidebar-demo",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-demo.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-header": {
    name: "sidebar-header",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-header.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-header.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-footer": {
    name: "sidebar-footer",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-footer.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-footer.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-group": {
    name: "sidebar-group",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-group.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-group.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-group-collapsible": {
    name: "sidebar-group-collapsible",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-group-collapsible.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-group-collapsible.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-group-action": {
    name: "sidebar-group-action",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-group-action.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-group-action.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-menu": {
    name: "sidebar-menu",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-menu.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-menu.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-menu-action": {
    name: "sidebar-menu-action",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-menu-action.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-menu-action.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-menu-sub": {
    name: "sidebar-menu-sub",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-menu-sub.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-menu-sub.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-menu-collapsible": {
    name: "sidebar-menu-collapsible",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-menu-collapsible.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-menu-collapsible.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-menu-badge": {
    name: "sidebar-menu-badge",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-menu-badge.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-menu-badge.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-rsc": {
    name: "sidebar-rsc",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-rsc.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-rsc.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sidebar-controlled": {
    name: "sidebar-controlled",
    description: "",
    type: "registry:internal",
    registryDependencies: undefined,
    files: [{
      path: "registry/product-ui/internal/sidebar-controlled.tsx",
      type: "registry:component",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/product-ui/internal/sidebar-controlled.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }